### ISSUE TITLE
日本語にしか見えないフォントのやつ....(他の技術者きてくれ...)

### ISSUE THREAD

**Issue by TAMAGO55123** [The-Infinitys/blog-data#2]
9行目のこれ...
`font-family: electroharmonix;`
こうでは？
`font-family: 'electroharmonix';`

んで13~15を
`*{
      font-family: 'electroharmonix', sans-serif;
}`
にするのでは？？

**Comment by The-Infinitys** [comment]
なるほど…やってみる

**Comment by The-Infinitys** [comment]
助けてくれ

**Comment by TAMAGO55123** [comment]
のわ、だめなんか

**Comment by TAMAGO55123** [comment]
ttfへのリンクをこれにするとか
https://the-infinitys.f5.si/blog-data/2024-5/Japanese-like-font/electroharmonix.ttf

**Comment by The-Infinitys** [comment]
やってみよう

**Comment by TAMAGO55123** [comment]
あああああだめやああああ

**Comment by TAMAGO55123** [comment]
じゃあこうだ
https://github.com/The-Infinitys/blog-data/raw/main/2024-5/Japanese-like-font/electroharmonix.ttf

**Comment by The-Infinitys** [comment]
それ行けるのか...?

**Comment by TAMAGO55123** [comment]
もうヤケクソである

**Comment by TAMAGO55123** [comment]
あ、検索したら

> .ttf：'truetype'
formatの中truetypeにするらしい

**Comment by TAMAGO55123** [comment]
😫

**Comment by The-Infinitys** [comment]
放棄するのであります
